name: Deploy Spider

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run mypy
        run: |
          mypy .

      - name: Run ruff
        run: |
          ruff .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t methuselahnwodobeh/ct_spider_i .

      - name: Tag Docker image
        run: docker tag methuselahnwodobeh/ct_spider_i methuselahnwodobeh/ct_spider_i:latest

      - name: Push Docker image to Docker Hub
        run: docker push methuselahnwodobeh/ct_spider_i

    deploy:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - name: Decode SSH Key
          run: echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > key.pem

        - name: Set SSH Key Permissions
          run: chmod 400 key.pem

        - name: Deploy to EC2
          uses: appleboy/ssh-action@v0.1.9
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: key.pem
            script: |
              docker pull methuselahnwodobeh/ct_spider_i
              docker stop ct_spider_i || true
              docker rm ct_spider_i || true
              docker run -d --name ct_spider_i methuselahnwodobeh/ct_spider_i